environment:
  LJT_VERSION: 2.1.3
  LJT_64BIT_SDK: "https://sourceforge.net/projects/libjpeg-turbo/files/%LJT_VERSION%/libjpeg-turbo-%LJT_VERSION%-vc64.exe"
  LJT_32BIT_SDK: "https://sourceforge.net/projects/libjpeg-turbo/files/%LJT_VERSION%/libjpeg-turbo-%LJT_VERSION%-vc.exe"

install:
  - cmd: >-
      mkdir c:\installers

      mkdir c:\temp

      choco install -y InnoSetup

      curl -fSL -o c:\installers\libjpeg-turbo-vc64.exe "%LJT_64BIT_SDK%"

      c:\installers\libjpeg-turbo-vc64.exe /S

      curl -fSL -o c:\installers\libjpeg-turbo-vc.exe "%LJT_32BIT_SDK%"

      c:\installers\libjpeg-turbo-vc.exe /S

      set INCLUDE=c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include;c:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared;c:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;c:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um

      set LIB=c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\amd64;c:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64;c:\Program Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64

      set PATH=c:\Program Files (x86)\Inno Setup 6;c:\msys64\usr\bin;c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64;c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE;c:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;%PATH%

      set MSYSTEM=MINGW32

      bash -c "pacman --noconfirm -S unzip"

      git clone --depth=1 https://github.com/TurboVNC/buildscripts.git -b main c:/buildscripts

cache:
  - c:\msys64\home\%USERNAME%\.openjdk

build_script:
  - cmd: >-
      for /f %%i in ('"cygpath %CD%"') do set MINGWPATH=%%i

      bash c:/buildscripts/buildvnc -d %MINGWPATH% -b /c/vnc.nightly -v

      move c:\vnc.nightly\files\*.tar.gz .

      move c:\vnc.nightly\files\*.exe .

      move c:\vnc.nightly\files\*.html .

      move c:\vnc.nightly\log-windows.txt .

artifacts:
  - path: '*.tar.gz'
    name: Source tarball

  - path: '*.exe'
    name: TurboVNC Viewer

  - path: 'log-windows.txt'
    name: Build log

  - path: 'index.html'
    name: MD5 checksums

test: off
